hmcts/cnp-plum-recipes-service

- Jenkinsfile_CNP
- build.gradle
- charts/plum-recipe-backend/Chart.yaml
- charts/plum-recipe-backend/requirements.yaml
- charts/plum-recipe-backend/values.template.yaml
- src/main/resources/bootstrap.yaml
https://tools.hmcts.net/jira/browse/RPE-1006
```
[ ] Yes
[x] No
```
> Update chart to use in aat aks environment

- src/main/resources/bootstrap.yaml
https://tools.hmcts.net/jira/browse/RPE-1006
```
[ ] Yes
[x] No
```
> Remove environment suffix.

- build.gradle
- dependency-check-suppressions.xml
> Update spring version. Add cve suppression (no fix yet)

- charts/plum-recipe-backend/Chart.yaml
- charts/plum-recipe-backend/requirements.yaml
- charts/plum-recipe-backend/values.aat.template.yaml
- charts/plum-recipe-backend/values.preview.template.yaml
- charts/plum-recipe-backend/values.template.yaml
- charts/plum-recipe-backend/values.yaml
https://tools.hmcts.net/jira/browse/RPE-1034
update this repo chart version to enable installation by Helm
update java-chart to the latest version
Added refactoring for preview configurations
```
[ ] Yes
[ x] No
```
> Upgrade Java chart, refactor Preview configurations

- build.gradle
Disable .Net scanning 
Disable .Net Scanning 
```
[ ] Yes
[ x] No
```
> disable .Net scanning

- charts/crumble-recipe-backend/Chart.yaml
- charts/crumble-recipe-backend/requirements.yaml
- charts/crumble-recipe-backend/values.aat.template.yaml
- charts/crumble-recipe-backend/values.preview.template.yaml
- charts/crumble-recipe-backend/values.yaml
Adding chart for crumble as Jenkins pipeline tests will use crumble as product 
```
[ ] Yes
[x] No
```
> Adding chart for crumble

- charts/crumble-recipe-backend/requirements.yaml
> Use hmctssandbox for crumble

- Jenkinsfile_CNP
- Jenkinsfile_pipeline_test
- src/test/java/uk/gov/hmcts/reform/rhubarb/recipes/ApplicationTests.java
> Disable skip image build for sandbox environment

- infrastructure/main.tf
Previously overwrote rhubarb's API config
```
[ ] Yes
[ ] No
```
> Update API mgmt name to plum

- infrastructure/deploymentTarget/main.tf
- infrastructure/main.tf
https://tools.hmcts.net/jira/browse/RPE-1069
Oops forgot to set the java version for Azure before..
```
[ ] Yes
[ ] No
```
> Add missing java version setting for Azure

- charts/crumble-recipe-backend/values.yaml
- charts/plum-recipe-backend/values.yaml
Fixing image paths
```
[ ] Yes
[x] No
```
> Fixing image paths

- charts/crumble-recipe-backend/values.aat.template.yaml
- charts/crumble-recipe-backend/values.saat.template.yaml
- charts/plum-recipe-backend/values.aat.template.yaml
- charts/plum-recipe-backend/values.saat.template.yaml
Fixing typo for password field in charts
```
[ ] Yes
[x] No
```
> Fixing typo for password field in charts

- charts/crumble-recipe-backend/values.aat.template.yaml
- charts/crumble-recipe-backend/values.saat.template.yaml
- charts/plum-recipe-backend/values.aat.template.yaml
- charts/plum-recipe-backend/values.saat.template.yaml
Adding ssl require on AAT templates
```
[ ] Yes
[x] No
```
> Adding ssl require on AAT templates

- Jenkinsfile_pipeline_test
Reverting legacy deployments flags post test
```
[ ] Yes
[x] No
```
> Reverting legacy deployments flags post test

- infrastructure/.gitignore
- infrastructure/main.tf
Couple of other cleanup changes, all in separate commits
> Fix api mgmt

- Jenkinsfile_CNP
- charts/crumble-recipe-backend/values.sandbox.template.yaml
testing new subscription library changes and adding aad to new sandbox
```
[ ] Yes
[x] No
```
> testing new subscription changes and adding aad

- charts/crumble-recipe-backend/Chart.yaml
- charts/crumble-recipe-backend/requirements.yaml
- charts/plum-recipe-backend/Chart.yaml
- charts/plum-recipe-backend/requirements.yaml
Bumping java chart to include pod identity.
```
[ ] Yes
[x] No
```
> bumping java chart

- charts/plum-recipe-backend/values.aat.template.yaml
> Add pod identity to AAT

- build.gradle
- dependency-check-suppressions.xml
> Update dependencies for owasp

- build.gradle
- checkstyle.xml
> Bump checkstyle

- charts/plum-recipe-backend/Chart.yaml
- charts/plum-recipe-backend/requirements.yaml
> Use new chart-java with test jobs

- charts/plum-recipe-backend/Chart.yaml
- charts/plum-recipe-backend/requirements.yaml
[[AB#591](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/591)]
```
[ ] Yes
[x] No
```
> Use new chart-java for test jobs

- charts/crumble-recipe-backend/Chart.yaml
- charts/plum-recipe-backend/Chart.yaml
https://helm.sh/docs/developing_charts/#the-chart-yaml-file
> Add apiVersion required in helm 2.15.0

- charts/crumble-recipe-backend/values.preview.template.yaml
- charts/plum-recipe-backend/values.preview.template.yaml
- dependency-check-suppressions.xml
> Adding suppression for tomcat cve

- dependency-check-suppressions.xml
[AB#697](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/697)
Added supression for CVE-2020-5398. 
```
[ ] Yes
[x] No
```
> Added suppresion for CVE-2020-5398

- .dependabot/config.yml
Added dependabot
```
[ ] Yes
[x] No
```
> Added dependabot

- build.gradle
[AB#697](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/697)
Upgraded spring boot due to dependency vulnerabilities referenced in:
https://nvd.nist.gov/vuln/detail/CVE-2020-5398
```
[ ] Yes
[x] No
```
> Upgraded Spring Boot 2.2.4

- Jenkinsfile_pipeline_test
- infrastructure/main.tf
- infrastructure/saat.tfvars
- infrastructure/sprod.tfvars
> clean up unused

- build.gradle
- charts/plum-recipe-backend/Chart.yaml
- charts/plum-recipe-backend/values.yaml
- gradle/wrapper/gradle-wrapper.properties
- gradlew
- gradlew.bat
This change was initiated to fix a CVE in spring security, but upgrading spring boot requires upgrading Gradle hence I'm combining these changes.
> Upgrade Gradle to 6.4.1 and spring boot to 2.3.0

- .github/renovate.json
> Add helm requirements renovate

- .github/renovate.json
> Add gradlew for renovate

- charts/crumble-recipe-backend/Chart.yaml
- charts/crumble-recipe-backend/requirements.yaml
- charts/plum-recipe-backend/Chart.yaml
- charts/plum-recipe-backend/requirements.yaml
> Upgrade helm charts

- .github/workflows/swagger.yaml
- build.gradle
- config/pmd/ruleset.xml
- src/main/java/uk/gov/hmcts/reform/rhubarb/recipes/config/SwaggerConfiguration.java
- src/main/java/uk/gov/hmcts/reform/rhubarb/recipes/endpoint/EndpointExceptionHandler.java
- src/test/functional/java/uk/gov/hmcts/reform/rhubarb/functional/HealthCheckTest.java
- src/test/functional/java/uk/gov/hmcts/reform/rhubarb/functional/RecipesTest.java
- src/test/gateway/java/uk/gov/hmcts/reform/rhubarb/api/GetAllRecipesTest.java
- src/test/java/uk/gov/hmcts/reform/rhubarb/recipes/ApplicationTests.java
- src/test/java/uk/gov/hmcts/reform/rhubarb/recipes/SwaggerPublisher.java
> Use Junit 5 , fixing swagger publish

- src/main/java/uk/gov/hmcts/reform/rhubarb/recipes/endpoint/RecipeController.java
> remove unused property

- build.gradle
> Force jaxb-osgi version upgrade

- Jenkinsfile_CNP
Reverts hmcts/cnp-plum-recipes-service#156
> Revert "Test helm chart publish to git"

- Jenkinsfile_CNP
> Enable git charts

- Jenkinsfile_CNP
Reverts hmcts/cnp-plum-recipes-service#159
> Revert "change to git charts"

- Jenkinsfile_CNP
Reverts hmcts/cnp-plum-recipes-service#161
> Revert "Revert "change to git charts""

- Jenkinsfile_CNP
> Revert pipeline branch test

- charts/plum-recipe-backend/Chart.yaml
Bumping java version to 3.4.4
```
[ ] Yes
[x] No
```
> Bumping java version to 3.4.4

- charts/plum-recipe-backend/values.preview.template.yaml
- src/main/resources/bootstrap.yaml
https://tools.hmcts.net/jira/browse/DTSPO-161
add configuration so that toffee db config is picked up by the app
```
[ ] Yes
[X] No
```
> DTSPO-161 - toffee db config

- build.gradle
> Fix gradle build

- infrastructure/main.tf
> Revert db module test

- infrastructure/main.tf
> create postgresdb v11

- infrastructure/main.tf
- infrastructure/variables.tf
Postgres11 work not needed yet. Currently pipeline is broken.
```
[ ] Yes
[X] No
```
> Postgres11 work not needed yet. Currently pipeline is broken.

- infrastructure/main.tf
Additions for Postgres v11 
```
[ ] Yes
[X] No
```
> add postgres11

- infrastructure/main.tf
Update postgres v11 module source
```
[ ] Yes
[X] No
```
> Update postgres v11 module source

- charts/crumble-recipe-backend/Chart.yaml
- charts/plum-recipe-backend/Chart.yaml
Upgrade java chart
https://build.platform.hmcts.net/blue/organizations/jenkins/HMCTS_CNP%2Fcnp-plum-recipes-service/detail/PR-329/2/pipeline/
```
[ ] Yes
[ x] No
```
> Chart-java upgrade to 3.4.6

- charts/plum-recipe-backend/Chart.yaml
**Does this PR introduce a breaking change?**
```
[ ] Yes
[x] No
```
> Upgrade Plum to Use Latest Java Chart 3.4.8

- build.gradle
https://tools.hmcts.net/jira/browse/CCD-1131
Added a new Gradle task of highLevelDataSetup for cnp-jenkins-library to run successfully.
```
[ ] Yes
[x] No
```
> adaptation of highLevelDataSetup

- build.gradle
https://tools.hmcts.net/jira/browse/DTSPO-2706
updated tomcat embed version.
```
[ ] Yes
[ X] No
```
> update to tomcat embed version

- README.md
dummy readme update to test flux v1
```
[ ] Yes
[x ] No
```
> DTSPO-5156 - test dummy update for flux v1

- README.md
revert test readme update - for flux v1 testing
```
[ ] Yes
[x ] No
```
> DTSPO-5156 - Revert test update

- charts/plum-recipe-backend/Chart.yaml
https://tools.hmcts.net/jira/browse/DTSPO-2201
Upgraded chart-java to 3.6.1-beta to test startup probes
```
[ ] Yes
[x ] No
```
> DTSPO-2201 Upgrade chart-java to 3.6.1-beta - Startup probes test

- charts/crumble-recipe-backend/Chart.yaml
- charts/plum-recipe-backend/Chart.yaml
(https://tools.hmcts.net/jira/browse/DTSPO-6653)
Preparation work for PTL jenkins aks upgrade, running plum build as a test.
```
[ ] Yes
[x] No
```
> Dtspo 6653 update plum java version

- charts/crumble-recipe-backend/values.yaml
- charts/plum-recipe-backend/Chart.yaml
- charts/plum-recipe-backend/values.yaml
To clear v10 dbs
```
[ ] Yes
[ x] No
```
> Point at v11 postgres

- infrastructure/main.tf
> Clean up old v10 postgres

- build.gradle
- dependency-check-suppressions.xml
DTSPO-8276
Fix security checks:
- Update dependency-check-suppressions.xml
```
[ ] Yes
[X] No
```
> DTSPO-8276 - Fix security checks

- build.gradle
- dependency-check-suppressions.xml
Reverts hmcts/cnp-plum-recipes-service#507
> Revert "DTSPO-8276 - Fix security checks"

- charts/crumble-recipe-backend/Chart.yaml
- charts/plum-recipe-backend/Chart.yaml
- charts/plum-recipe-backend/values.preview.template.yaml
> Test java chart upgrades

- dependency-check-suppressions.xml
> Suppress CVE

- charts/crumble-recipe-backend/Chart.yaml
- charts/plum-recipe-backend/Chart.yaml
Testing failing with -alpha version of chart
```
[ ] Yes
[ x] No
```
> Java chart version corrections for preview testing

- charts/plum-recipe-backend/values.prod.template.yaml
https://tools.hmcts.net/jira/browse/DTSPO-8117
Adds tfvars file for prod values
> Adds tfvars file for prod values

- charts/plum-recipe-backend/values.prod.template.yaml
- infrastructure/main.tf
> Dtspo 8117 plum prod

- infrastructure/main.tf
> fix content format for swagger

- Jenkinsfile_CNP
Reverts hmcts/cnp-plum-recipes-service#605
> Revert "test collect-nightly-gatling branch"

- Jenkinsfile_nightly
Reverts hmcts/cnp-plum-recipes-service#607
> Revert "Test collect nightly gatling"

- charts/plum-recipe-backend/Chart.yaml
- dependency-check-suppressions.xml
> Bump library

- charts/plum-recipe-backend/Chart.yaml
Nodejs confirmed working with plum, testing java chart too for double check
```
[ ] Yes
[ ] No
```
> Bump library to test

- .github/workflows/swagger.yaml
Fixing swagger github action
```
[ ] Yes
[x] No
```
> Fix swagger action

- Jenkinsfile_CNP
- dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/DTSPO-11015
remove   the enableMasterTestBuild() call  to test if test build is skipped for new feature in jenkins shared library java pipeline
```
[ ] Yes
[ x] No
```
> test absence of enableMasterTestBuild() for new jenkins shared library feature

- Jenkinsfile_CNP
https://tools.hmcts.net/jira/browse/DTSPO-11015
adding enableTestDockerBuild() for functional test of Jenkins shared library after changes 
```
[ ] Yes
[x] No
```
> enableTestDockerBuild() functional test

- Jenkinsfile_CNP
https://tools.hmcts.net/jira/browse/DTSPO-11015
omit enableTestDockerBuild() function for default testing of new feature to Jenkins shared library
```
[ ] Yes
[ x] No
```
> omit enableTestDockerBuild() function for default testing

- Jenkinsfile_CNP
https://tools.hmcts.net/jira/browse/DTSPO-11015
omit enableTestDockerBuild() function for default testing
```
[ ] Yes
[x] No
```
> remove enableTestDockerBuild()

- Jenkinsfile_CNP
> Update jenkinsfile to test feature enabled

- .github/renovate.json
- Dockerfile
- build.gradle
> Upgrade spring boot and appinsights agent

- charts/plum-recipe-backend/Chart.yaml
- charts/plum-recipe-backend/values.yaml
> Upgrade chart

- charts/plum-recipe-backend/Chart.yaml
> Bump chart-java version

- build.gradle
- dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/DTSPO-7637
Add new suppression for CVE
> DTSPO-7637 - dependency updates

- Jenkinsfile_CNP
> Ignore test

- infrastructure/main.tf
- infrastructure/state.tf
- infrastructure/variables.tf
JIRA link (if applicable)
[DTSPO-13333](https://tools.hmcts.net/jira/browse/DTSPO-13333)
Change description
Adding postgresql flexible server to plum to test single to flex migration tool
```
[ ] Yes
[x] No
```
> DTSPO-13333 adding postgresql flexible server to plum

- charts/plum-recipe-backend/Chart.yaml
- charts/plum-recipe-backend/values.yaml
[DTSPO-13245](https://tools.hmcts.net/jira/browse/DTSPO-13245)
Updating connection to use flex server
```
[ ] Yes
[x] No
```
> DTSPO-13245 Updating access to postgres flexserver

- build.gradle
https://tools.hmcts.net/jira/browse/DTSPO-13332
Update dependency management plugin
Current version not working
```
[ ] Yes
[x] No
```
> DTSPO-13332 - Update dependency management plugin

- Jenkinsfile_CNP
- dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/DTSPO-13332
Suppress CVE-2016-1000027 vulnerability in spring-web 5.3.27 until patched
> DTSPO-13332 - Spring web CVE-2016-1000027 suppression

- infrastructure/main.tf
https://tools.hmcts.net/jira/browse/DTSPO-13580
Restore master branch on module
```
[ ] Yes
[x] No
```
> DTSPO-13580 - Restore postgres module branch

- Jenkinsfile_CNP
> Test PR -ignore

- .github/CODEOWNERS
Don't require codeowners for files and paths updated by renovate
```
[ ] Yes
[x] No
```
> Ignore files and paths updated by renovate

- charts/plum-recipe-backend/Chart.yaml
> workload identity change to test

- charts/plum-recipe-backend/Chart.yaml
DTSPO-13615
Update chart-java version
```
[ ] Yes
[ x ] No
```
> Change chart-java version

- charts/plum-recipe-backend/Chart.yaml
DTSPO-13615
Test workload identity changes
```
[ ] Yes
[ x ] No
```
> Dtspo 13615

- charts/crumble-recipe-backend/Chart.yaml
- charts/plum-recipe-backend/Chart.yaml
> Upgrade java version

- build.gradle
https://tools.hmcts.net/jira/browse/DTSPO-14034
Use plugin for gatling performance tests instead of docker image
```
[ ] Yes
[x] No
```
> DTSPO-14034 - Use gatling plugin

- build.gradle
Dependency fix check for Tomcat CVE-2023-42795 & CVE-2023-45648
> Dependency fix check for Tomcat CVE-2023-42795 & CVE-2023-45648

- charts/crumble-recipe-backend/Chart.yaml
- infrastructure/main.tf
https://tools.hmcts.net/jira/browse/DTSPO-15743
Build postgres flexible server with v15. seeing error on some builds - The usable ip address number [3] is less then required [4]
> Build postgres flexible server with v15

- infrastructure/main.tf
> Adding the fix for the subnet error

- build.gradle
> Bump tomcat & logback version

- build.gradle
Reverts hmcts/cnp-plum-recipes-service#913
> Revert "Update dependency checkstyle to v10.14.2"

- infrastructure/main.tf
Remove create_mode update as in place update it is not available for v16 currently
> Postgres v16 fix

- infrastructure/main.tf
- infrastructure/sandbox.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-17012
Change sbox to standard from basic, cant jump from basic to premium directly
> Change sbox to standard

- infrastructure/sandbox.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-17012
Have to set rdb false for now
> Have to set rdb false for now

- infrastructure/sandbox.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-17012
Change sbox to premium and enable rdb
> Change sbox to premium and enable rdb

- infrastructure/sandbox.tfvars
Scale back redis from premium to basic
> Scale back redis

- infrastructure/main.tf
Reverts hmcts/cnp-plum-recipes-service#1074
Testing completed successfully
> Revert "Test postgres flexible TF module enable_qpi feature against plum sbox flex server"

- build.gradle
- src/gatling/scala/simulations/uk/gov/hmcts/reform/rhubarb/performance/Environments.scala
- src/gatling/scala/simulations/uk/gov/hmcts/reform/rhubarb/performance/RhubarbReferenceSimulation.scala
N/A
[2025-07-07T09:46:45.447Z] java.lang.RuntimeException: Jitpack is no longer supported on the project. Please update to use Azure DevOps Artifacts following the guide at https://hmcts.github.io/cloud-native-platform/common-pipeline/publishing-libraries/java.html This change is enforced from 30/06/2025 
**CVE Suppression:** Are there any CVEs present in the codebase (either newly introduced or pre-existing) that are being intentionally suppressed or ignored by this commit?
> fix jitpack failure

- Jenkinsfile_nightly
See [PROJ-XXXXXX](https://tools.hmcts.net/jira/browse/PROJ-XXXXXX)
**CVE Suppression:** Are there any CVEs present in the codebase (either newly introduced or pre-existing) that are being intentionally suppressed or ignored by this commit?
> fix: add test url for zap

- infrastructure/sandbox.tfvars
See [DTSPO-27838](https://tools.hmcts.net/jira/browse/DTSPO-27838)
Upgrade Redis Sku from sbox to premium from basics
**CVE Suppression:** Are there any CVEs present in the codebase (either newly introduced or pre-existing) that are being intentionally suppressed or ignored by this commit?
> DTSPO 27838 - upgrade sbox sku to premium
